# Generated by Django 6.0 on 2025-12-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('hostel_block', models.CharField(choices=[('A Block', 'A Block'), ('C Block', 'C Block'), ('D1 Block', 'D1 Block'), ('D2 Block', 'D2 Block')], max_length=10)),
                ('room_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('hostel_block', models.CharField(choices=[('A Block', 'A Block'), ('C Block', 'C Block'), ('D1 Block', 'D1 Block'), ('D2 Block', 'D2 Block')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('hostel_block', models.CharField(choices=[('A Block', 'A Block'), ('C Block', 'C Block'), ('D1 Block', 'D1 Block'), ('D2 Block', 'D2 Block')], max_length=10)),
                ('room_no', models.CharField(blank=True, max_length=20, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='registrations.team')),
            ],
        ),
    ]
